[package]
name = "motion"
version = "0.1.0"
edition = "2021"

[dependencies]
mlua = { version = "0.10.0", features = ["lua54","vendored","send"] }
glam = { version = "0.29.2", features = ["fast-math", "serde"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_derive = "1.0.219"