[package]
name = "actionq-simple"
version = "0.1.0"
edition = "2024"

[dependencies]
macroquad = "0.4"

actionq-common = { path = "../actionq-common" }
actionq-motion = { path = "../actionq-motion" }
actionq-zed    = { path = "../actionq-zed"    }
